### ISSUE TITLE
Enable brute force detection?

### ISSUE THREAD

**Issue by symgryph** [micromata/dave#14]
If you were to log "User x failed to login" I could use fail2ban to stop evil users from brute forcing me. I could use a proxy, but was curios what you thought about adding this security feature?

**Comment by chclaus** [comment]
Hej @symgryph,

sorry for delay. Had a lot on my mind...
I really like your Idea. Would you implement the feature?

Best,
Christian

**Comment by symgryph** [comment]
Yes I would implement it. We currently use it for some of our developers to upload stuff. I would to get rid of the idiots who are trying to attack me.

**Comment by chclaus** [comment]
Nice! Thanks a lot. 😊

**Comment by symgryph** [comment]
I don’t know how to program unfortunately. I thought you meant help you test it.

**Comment by chclaus** [comment]
Hehe,

all good.  We'll get around that. I'm happy to leave it to you for testing :)

**Comment by chclaus** [comment]
Hej @symgryph,

I've added some unified log output and remote addresses to failed login attempts. You should now find the following three possiblities:

```
WARN[0023] User failed to login                          address=127.0.0.1 error="username not found or password empty" user=foo
WARN[0035] User failed to login                          address=127.0.0.1 error="Password doesn't match" user=user
WARN[0073] User failed to login                          address=127.0.0.1 error="user not found" user=foo
```

It would be nice if you could give your two cents to the improvement.

Best,
Christian

**Comment by symgryph** [comment]
does this support ipv6?

Thomas J Munn

**Comment by symgryph** [comment]
I’ll check in a new code tonight and see how it does.

Thomas J Munn

**Comment by chclaus** [comment]
Feature went into the current release
