### ISSUE TITLE
No users configured but authentication required 

### ISSUE THREAD

**Issue by schlamar** [micromata/dave#16]
If no users are configured I'm getting an authentication popup from my browser

**Comment by chclaus** [comment]
Hej @schlamar,

sorry for delay. Had a lot of work... Did you also remove the `users:` parent element?

Best,
Christian

**Comment by schlamar** [comment]
>Did you also remove the users: parent element?

I guess. Is that the issue?

**Comment by chclaus** [comment]
Hmm.... I first thought so. But can't reproduce it. What client are you using?

**Comment by schlamar** [comment]
Mhh if I remember correctly I tried various clients, including directly in the browser (Google Chrome).

**Comment by chclaus** [comment]
I close the Issue, due to the past time
