### ISSUE TITLE
Incorrect timestamp in getlastmodified

### ISSUE THREAD

**Issue by schlamar** [micromata/dave#17]
Dave is affected by this issue: https://github.com/golang/go/issues/25015

**Comment by chclaus** [comment]
Oh! Thanks for info @schlamar. I'll have a look

**Comment by samhocevar** [comment]
Hi! This issue was actually indirectly fixed a long time ago in 023c87c848e47b07c01e5f496d8b9afc169136d8, so I’m closing it.
