### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by dmotte** [micromata/dave#24]
Hi! First of all, thanks for this software! :smiley:

It would be great to have the image in the **Docker Hub**, so one can do a `docker pull` without building it manually every time. Thanks in advance for your attention

**Comment by idashevskii** [comment]
I join the offer

**Comment by chclaus** [comment]
Good Idea. I will take care of it.

**Comment by dmotte** [comment]
@chclaus if you need inspiration on how to build it automatically for different architectures (amd64, arm, etc.), see this link from one of my recent projects https://github.com/dmotte/docker-portmap-client/tree/main/.github/workflows

**Comment by chclaus** [comment]
Done. Results are here: https://hub.docker.com/repository/docker/micromata/dave/general

We currently have the issue, that the descriptions API of docker hub won't allow access tokens. https://github.com/peter-evans/dockerhub-description/issues/10

But i think the main part is solved ;)

**Comment by dmotte** [comment]
@chclaus Thanks for your work! This is extremely useful! I suggest adding a link to the Docker Hub page in the `README` file, maybe in the `Build and run with Docker` section :wink: Something like this:

```markdown
This image is also on **Docker Hub** as [`micromata/dave`](https://hub.docker.com/r/micromata/dave).
```

Result:

This image is also on **Docker Hub** as [`micromata/dave`](https://hub.docker.com/r/micromata/dave).

**Comment by chclaus** [comment]
Yeah.... missed this yesterday @dmotte. Thanks for the reminder. ;)
