### ISSUE TITLE
Willing to help maintain Dave

### ISSUE THREAD

**Issue by samhocevar** [micromata/dave#40]
Hi, we use Dave in production and are quite happy with it. I’d be willing to help maintain the software. I have decent Go experience, having ported the runtime to multiple platforms, and a pretty good software engineering experience.

A few disclaimers:
 - I would start working on smaller bugs / features that I think are worth working on: #29, #17, #13; you can see that I have already submitted a PR for #36.
 - I would probably not work on #10/#30 because the multiple possible LDAP binding scenarios make it difficult to get right. We successfully use Apache and nginx as authenticating (and caching) frontends for Dave instead.
 - I would get rid of the `vendor` directory, that’s 70 MiB of source data that probably no one needs; `go build` can fetch it.
 - I may consider removing the magefile in the long term, as its complexity seems to surpass its usefulness.

I’m happy to discuss this further. Let me know what you think!

**Comment by mischah** [comment]
Hej Sam, thanks for offering your help.That would be nice :octocat: ❤️

I’m pretty sure @chclaus will be happy to add you as outside collaborator to this project.

**Comment by chclaus** [comment]
Hi @samhocevar,

this are really good news! I think it's a good plan to start with smaller issues and it's just great when you can develop a piece of software that you use yourself. Good for you and good for the software 😉

Feel free to refactor and cleanup the build process.

I don't have much time anymore, unfortunately, and I think it's a shame. Dave deserves some more care and I really hope you can help there. 😀 

I think we have one open topic, the docker hub privileges. I would skip this a few days. Currently I have a flu 😉 

The github privileges are on their way. I wish you have a nice evening!

**Comment by samhocevar** [comment]
Thanks a lot! I’ve started cleaning up a bit and getting more familiar with the parts I haven’t used yet.

Just a reminder for me: I did a survey of the existing forks just in case, and here are the changes that are not just related to the outdated `go.mod`.
 - https://github.com/shynome/dave/commit/60557a02c7e305d1291a2c1df11a2d0571b49f9a https://github.com/shynome/dave/commit/74adaef25636ad2642b35d1bc57de12ca9aaac02 allow to specify plaintext passwords in the configuration (looks a bit dangerous)
 - https://github.com/ddmls/dave/commit/78c3312bb3fce2835c6be5966c82199d8f1c94e0 update Dockerfile to newer Alpine release
 - https://github.com/recall704/dave/commit/55f98d6a30bed8296d08858baf81d0c21ce9a7e0 update Dockerfile to use GitHub instead of DockerHub

**Comment by dxlr8r** [comment]
Also https://github.com/micromata/dave/pull/55

**Comment by mischah** [comment]
Thanks @samhocevar for your time and effort :octocat: ❤️
