### ISSUE TITLE
Usermanagement bei puredb of pureftp

### ISSUE THREAD

**Issue by nudeldudel** [micromata/dave#45]
Is there any chance to alternate the user management to a puredb file by pure ftp. Therefore, the config.yml should be obsolete. 

The case-scenario is a docker-container, which conclude pureftp and dave to a simple data storage especial for document-scanning.

**Comment by mischah** [comment]
Isn’t that a pretty extraordirary case?

@samhocevar @chclaus 
Is this something which should Dave handle itself?

**Comment by lingej** [comment]
@nudeldudel this ist just an example to create the user yaml structure out of your pureftpd password file

` cat /etc/pure-ftpd/pureftpd.passwd | awk '{split($0,a,":"); printf "  %s:\n    password: \"%s\"\n    subdir: \"%s\"\n", a[1], a[2], a[6] }'`

Joerg

**Comment by samhocevar** [comment]
I agree that puredb is not a useful interchange format and is far too specific for Dave to support. Generating the user databases for both services from a common source seems like the better approach.
